export const CONSTANTS = {
  TRIAL_PERIOD_DAYS: 14,
  SUBSCRIPTION_PRICE_GHS: 250, // Standard subscription price in GHS
  MAX_LOGIN_ATTEMPTS: 5,
  JWT_DEFAULT_EXPIRY: '7d',
  RATE_LIMITS: {
    GLOBAL_WINDOW_MS: 15 * 60 * 1000,
    GLOBAL_MAX: 100,
    PUBLIC_ORDER_WINDOW_MS: 60 * 1000,
    PUBLIC_ORDER_MAX: 60,
  }
};
